repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: check-symlinks
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.11.1  # Use the sha / tag you want to point at
    hooks:
    - id: eslint
      exclude: >
              (?x)^(
                  browser-polyfill.min.js
              )$
